[[headers]]
for = "/.netlify/functions/*"
  [headers.values]
  Access-Control-Allow-Origin = "https://ubiqitum-freemium.webflow.io"
  Access-Control-Allow-Methods = "POST, GET, OPTIONS"
  Access-Control-Allow-Headers = "Content-Type"
  Access-Control-Max-Age = "86400"
